#:schema node_modules/wrangler/config-schema.json
name = "ai-content-detector"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

# Environment variables
[vars]
DEBUG = "true"
APP_PORT = "8000"
